server:
  port: 8888

capitaldb:
  addr: localhost
  port: 5432
  user: postgres
  password: postgres
  db: capital
  migrationdir: tools/migrate/migrations/capital

logger:
  level: debug

youtube_client_secret:
  client_id: "753008862528-6j4s4j1l99phtikjs5fn6u2qaka5abii.apps.googleusercontent.com"
  project_id: "lucky-kayak-289315"
  auth_uri: "https://accounts.google.com/o/oauth2/auth"
  token_uri: "https://oauth2.googleapis.com/token"
  auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
  client_secret: "NAzsEBJifGUbIzLbQLTVzkZH"

youtube_video_resource:
  filename: "" # Name of video file to upload
  title: "Test Title" # Video title
  description: "Test Description" # Video description
  category: "22" # Video category
  keywords: "" # Comma separated list of video keywords
  privacy:  "unlisted" # Video privacy status