// Code generated by odzo, but your can (must) modify it.
package config

import (
	"github.com/Odar/capital-lurker/internal/server"
	"github.com/Odar/capital-lurker/pkg/db"
)

type Config struct {
	Server    *server.Config
	CapitalDB *db.Config
	Logger    *Logger
}

type Logger struct {
	Level string
}
