// Code generated by odzo, but your can (must) modify it.
package config

import (
	"github.com/Odar/capital-lurker/internal/server"
)

type Config struct {
	Server *server.Config
	Logger *Logger
}

type Logger struct {
	Level string
}
